RHIROS #435 - Update is_configured api to serve system stats
RedHatInsights/ros-backend pull request #151
Opened 2021-12-16 13:03 UTC by apuntamb

2021-12-16 13:37 UTC, saltgen commented
LGTM :confetti_ball: 
Tested locally :+1:

2021-12-16 13:37 UTC, saltgen approved these changes

2021-12-16 13:39 UTC, PreetiW reviewed
have left a small query regarding count.

2021-12-17 07:27 UTC, apuntamb commented on ros/api/v0/hosts.py
> +            'count': system_count,
@kgaikwad Let's keep the count same here as that in the /systems api? What do you think?

2021-12-17 08:28 UTC, PreetiW commented on ros/api/v0/hosts.py
> +            'count': system_count,
+1 from my side to keep the count same as that in /systems api

2021-12-17 10:28 UTC, kgaikwad commented on ros/api/v0/hosts.py
> +            'count': system_count,
> @kgaikwad Let's keep the count same here as that in the /systems api? What do you think?

@apuntamb  -  currently it's same count, right?

2021-12-17 12:42 UTC, apuntamb commented on ros/api/v0/hosts.py
> +            'count': system_count,
@kgaikwad When we list systems using the` /systems` API they do not show any stale system, if present in the DB. But, in the `/is_configured` API, we can list all systems whether stale or fresh.

2021-12-17 14:17 UTC, kgaikwad commented on ros/api/v0/hosts.py
> +            'count': system_count,
@apuntamb - Could you point me source code where it filters of stale systems?

2021-12-17 14:40 UTC, kgaikwad commented
@apuntamb - could you please rebase and resolve conflicts?

2021-12-17 14:41 UTC, apuntamb commented on ros/api/v0/hosts.py
> +            'count': system_count,
@kgaikwad IMO https://github.com/RedHatInsights/ros-backend/blob/main/ros/api/v1/hosts.py#L106-L119

2021-12-17 14:42 UTC, kgaikwad requested changes
Also, openapi.json - https://github.com/RedHatInsights/ros-backend/blob/main/ros/openapi/openapi.json#L297 needs to be updated.

2021-12-17 14:46 UTC, kgaikwad commented on ros/api/v0/hosts.py
> +            'count': system_count,
> @kgaikwad IMO https://github.com/RedHatInsights/ros-backend/blob/main/ros/api/v1/hosts.py#L106-L119

@apuntamb  - I don't think this is stale systems filtering. Let's keep as it is for now.

2021-12-17 15:32 UTC, kgaikwad approved these changes
Thanks @apuntamb!

2021-12-17 15:32 UTC, merged