RHIROS-655 update prometheus metrics with org_id
RedHatInsights/ros-backend pull request #237
Opened 2022-06-28 09:44 UTC by r14chandra

2022-07-07 08:00 UTC, saltgen commented
@r14chandra Shall we add an unittest for this one, feel free to update the ones Kavita has previously added.

2022-07-15 10:01 UTC, kgaikwad requested changes

2022-07-15 10:03 UTC, kgaikwad commented on ros/processor/insights_engine_result_consumer.py
> +                    reporter=self.reporter, org_id=account.account
ditto

2022-07-15 10:23 UTC, kgaikwad commented
> @r14chandra Shall we add an unittest for this one, feel free to update the ones Kavita has previously added.

@saltgen - Could you create separate ticket for it. Currently there is no any test to check these custom metrics.
We can handle it separately.
Merging this change to verify current metrics and Grafana dashboard.

2022-07-15 10:23 UTC, kgaikwad approved these changes

2022-07-15 10:24 UTC, merged