RHIROS-502 api_version endpoint
RedHatInsights/ros-backend pull request #363
Opened 2023-09-14 05:55 UTC by srdeotarse

## api_version endpoint :boom:

[RHIROS-502](https://issues.redhat.com/browse/RHIROS-502) [BE] | API Version Endpoint

Add api_version endpoint to return reponse -

branch:
commit_sha:
commit_timestamp:
api_version:
deployed_at: 

### Endpoint: 

``/api/ros/v1/api_version``

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2023-09-14 14:29 UTC, saltgen requested changes

2023-09-14 14:29 UTC, saltgen commented on clowdapp.yaml
> +            value: "3"
You'll need to define these as parameters at the end of this file, like so

```
- description: organisation/owner-name of the GitHub repo
  name: GITHUB_OWNER
  value: "RedHatInsights"
```

Then use those here,

```
- name: GITHUB_OWNER
  value: ${GITHUB_OWNER}
```
I suggest adding these after `Feature flags` vars in a new section at the end.

2023-09-14 14:29 UTC, saltgen commented on ros/api/v1/api_version.py
> +from flask import jsonify
As per design guidelines, standard package import should be on top, 

```
from flask import jsonify
```

Then third party imports 

```
from flask_restful import Resource
from k8s_deployment_status import DeploymentStatus
```

And finally app imports

```
from ros.extensions import metrics
from ros.lib.config import API_VERSION
```
**Note:** These are not formal PEP8 rules, but are common best practices and conventions.

2023-09-14 14:29 UTC, saltgen commented on ros/api/routes.py
> +    api.add_resource(ApiVersion, f'/api/ros/{API_VERSION}/api_version')
@kgaikwad Would like to know your thoughts on global value for `API_VERSION`, would this become a challenge if 
endpoints get versioned differently in future?

2023-09-15 09:05 UTC, saltgen requested changes

2023-09-15 09:05 UTC, saltgen commented on clowdapp.yaml
> +# api_deployment_version endpoint
```suggestion
# Deployment version
```

2023-09-20 03:47 UTC, r14chandra requested changes

2023-09-20 03:47 UTC, r14chandra commented on pyproject.toml
> +k8s-deployment-status = "^0.0.6"
You can add this package in the [Github action](https://github.com/RedHatInsights/ros-backend/blob/main/.github/workflows/build_with_latest_direct_deps.yml) file for direct dependency as tests are failing for it.

2023-09-22 14:07 UTC, upadhyeammit commented on ros/api/v1/api_deployment_version.py
> +        pdb.set_trace()
Remove pdb :D

2023-09-22 14:07 UTC, upadhyeammit commented on ros/lib/config.py
> +API_VERSION = 'v1'
In future we may get more than one api version and both could be supported? can we depend on api paths maybe to get verion and actually show all deployed api versions?

2023-09-28 08:06 UTC, r14chandra requested changes

2023-09-28 08:06 UTC, r14chandra commented on .github/workflows/build_with_latest_direct_deps.yml
> +        k8s-deployment-status = "^0.0.6"
```suggestion
        k8s-deployment-status = "*"
```

2023-10-04 06:09 UTC, r14chandra commented
\retest

2023-10-31 17:50 UTC, kgaikwad requested changes
@srdeotarse  - PR facing few conflicts. Please have a look.

2024-07-05 18:10 UTC, closed without merging

2024-07-05 18:10 UTC, kgaikwad commented
Closing this PR as I don't not see any pr updates since long time.