add constants in one file
RedHatInsights/ros-backend pull request #378
Opened 2023-10-04 06:16 UTC by r14chandra

2023-10-04 13:14 UTC, srdeotarse reviewed
@r14chandra Thanks for the PR!

I have added my suggestions related to reducing code redundancy. But, I want to know whether we have any particular reason to have both``SystemStates.SYSTEM_STATES_EXCEPT_EMPTY`` and ``SystemStatesWithKeys.SYSTEM_STATES`` when only the later can be used wherever first one is used?

2023-10-04 13:14 UTC, srdeotarse commented on ros/lib/constants.py
> +class SystemStates(Enum):
I can see that values ("Oversized",  "Undersized" etc) of different keys in ``SYSTEM_STATES`` is similar to elements in ``SYSTEM_STATES_EXCEPT_EMPTY``. We can avoid code redundancy by using  ``SystemStatesWithKeys.SYSTEM_STATES.value.values()`` where we are using ``SystemStates.SYSTEM_STATES_EXCEPT_EMPTY.value`` to iterate over values.

2023-10-04 13:14 UTC, srdeotarse commented on ros/api/v1/hosts.py
> +                if state not in SystemStates.SYSTEM_STATES_EXCEPT_EMPTY.value:
We can add ``SystemStatesWithKeys.SYSTEM_STATES.value.values()`` here as suggested in ``constants.py`` file

2023-10-04 13:14 UTC, srdeotarse commented on ros/api/v1/hosts.py
> +            filters.append(System.state.in_(SystemStates.SYSTEM_STATES_EXCEPT_EMPTY.value))
Similar here as well.

2023-10-06 04:54 UTC, srdeotarse commented
@r14chandra Just reviewed your PR after the update. Thanks for considering suggested changes. Looks good to me ✅

2023-10-06 05:05 UTC, r14chandra commented
\retest

2023-10-06 05:25 UTC, r14chandra commented
/retest

2023-10-06 06:36 UTC, upadhyeammit requested changes

2023-10-06 06:36 UTC, upadhyeammit commented on ros/lib/constants.py
> +    OPTIMIZED_SYSTEM = "OPTIMIZED"
Do we require dict in Enum? as example,
~~~
>>> class TestEnum(Enum):
...     CAT="TOM"
...     DOG="GOOFY"
... 
>>> TestEnum.CAT
<TestEnum.CAT: 'TOM'>
>>> TestEnum.DOG
<TestEnum.DOG: 'GOOFY'>
>>> TestEnum.__members__.values()
dict_values([<TestEnum.CAT: 'TOM'>, <TestEnum.DOG: 'GOOFY'>])
>>> TestEnum._member_names_
['CAT', 'DOG']
~~~

2023-10-06 06:36 UTC, upadhyeammit commented on ros/lib/constants.py
> +    )
Same we don't require dict?

2023-10-06 06:36 UTC, upadhyeammit commented on ros/lib/constants.py
> +EVENT_TYPE = "new-suggestion"
I understand these are few vars, however we can still go ahead with separate Enum class for these to maintain the consistency?

2023-10-11 13:06 UTC, r14chandra commented
Thanks @srdeotarse @upadhyeammit  for the review!

2023-10-11 13:07 UTC, merged