Refs #RHIROS-1231 - job to downgrade and rerun migration
RedHatInsights/ros-backend pull request #386
Opened 2023-10-17 07:34 UTC by upadhyeammit

## Why do we need this change? :thought_balloon:

This should help to rerun migration in stage env to correct the top_candidates entries of performance_profile table.

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2023-10-17 07:36 UTC, upadhyeammit commented
I just have feeling that we should comment Processor and api pods in this pr and then let the job run. After that we would have another pr which would uncomment the Processor and api pods? what do you think @kgaikwad @r14chandra . @patilsuraj767 would like to know your thoughts as well! thanks!

2023-10-17 08:14 UTC, kgaikwad requested changes

2023-10-17 08:14 UTC, kgaikwad commented on clowdapp.yaml
> +        args: ["-c", "export FLASK_APP=manage.py && poetry run flask db downgrade && poetry run flask db upgrade"]
@upadhyeammit  - Could you please provide a particular revision into above commands for which you want to perform `downgrade & upgrade` ?

2023-10-18 08:39 UTC, r14chandra reviewed
@upadhyeammit Can we close this PR as it is not required?

2023-10-18 11:12 UTC, closed without merging