Fixes #RHINENG-5028 - support multiple kafka servers
RedHatInsights/ros-backend pull request #409
Opened 2023-12-07 10:07 UTC by upadhyeammit

## Why do we need this change? :thought_balloon:

The platform now has multiple kafka servers, the change is to support new additional servers/all servers

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2023-12-07 12:25 UTC, upadhyeammit commented
We had group.id and enable.auto.commit for producer as well, as per the logs its not required. I can also see one more ERROR of CLOUDWATCH, however not sure if that should be fixed in this pull request,
~~~
2023-12-07 11:46:38,372 - ERROR - commence_cw_log_streaming - CLOUDWATCH LOGGING - Insufficient constant values
2023-12-07 11:46:38,374 - INFO - run - PROCESSING ENGINE RESULTS - Processor is running. Awaiting msgs.
%4|1701949598.375|CONFWARN|rdkafka#producer-2| [thrd:app]: Configuration property group.id is a consumer property and will be ignored by this producer instance
%4|1701949598.375|CONFWARN|rdkafka#producer-2| [thrd:app]: Configuration property enable.auto.commit is a consumer property and will be ignored by this producer instance
~~~

2023-12-11 08:32 UTC, upadhyeammit commented
/retest

2023-12-12 05:25 UTC, r14chandra requested changes

2023-12-12 05:25 UTC, r14chandra commented on ros/lib/produce.py
> +    producer = Producer(kafka_auth_config())
Any particular reason for omitting `group.id` and `enable.auto.commit` attributes from here?

2023-12-12 07:57 UTC, r14chandra commented on ros/lib/produce.py
> +    producer = Producer(kafka_auth_config())
Okay, I missed your above comment. It makes sense to remove it.

2023-12-12 08:07 UTC, r14chandra approved these changes
LGTM!

2023-12-13 11:06 UTC, upadhyeammit commented
Thanks Rohini for the review! Merging this now!

2023-12-13 11:06 UTC, merged