RHIROS 217 - Fix core_collect errors
RedHatInsights/ros-backend pull request #92
Opened 2021-07-21 12:24 UTC by apuntamb

2021-07-22 08:24 UTC, kgaikwad requested changes

2021-07-22 08:43 UTC, apuntamb commented on ansible-playbooks/ros_install_and_set_up.yml
> +      register: core_collect
done

2021-07-27 09:11 UTC, kgaikwad commented
@apuntamb - could you confirm if all playbooks run successfully in check-mode without an error?

2021-07-27 12:11 UTC, apuntamb commented
> @apuntamb - could you confirm if all playbooks run successfully in check-mode without an error?

@kgaikwad Yeah, it works fine for all three playbooks in check mode.

2021-07-27 13:09 UTC, merged

2021-07-27 13:09 UTC, kgaikwad commented
Thanks @apuntamb :+1: :ok_hand: